### ISSUE TITLE
Issue google search

### ISSUE THREAD

**Issue by tanyafilo** [uchicago-computation-workshop/Fall2020#4]
Hey, may you help me with my own issue?
I'm trying to scrape large amount of results in Google, but I reach a limit of XXX with the message :

"In order to show you the most relevant results, we have omitted some entries very similar to the XXX already displayed.
If you like, you can repeat the search with the omitted results included."

I'm trying to get through 1000 results.
Any advises? clues?
Thanks ahead.

**Comment by shevajia** [comment]
Could you post your question and perhaps also a screenshot of your problem on MA Connect?
